# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mnc Weather Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Connect to ER

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Retrieve weather observations from GMMF

# %%
# parameters

subject_observations_params = dict()

# %%
# call the task


subject_observations = (
    get_subjectgroup_observations.set_task_instance_id("subject_observations")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        filter="clean",
        client=er_client_name,
        time_range=time_range,
        raise_on_empty=False,
        include_details=False,
        include_subjectsource_details=False,
        subject_group_name="ER2ER - From GMMF",
        **subject_observations_params,
    )
    .call()
)


# %% [markdown]
# ## Extract precipitation data

# %%
# parameters

extract_precipitation_params = dict()

# %%
# call the task


extract_precipitation = (
    extract_value_from_json_column.set_task_instance_id("extract_precipitation")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=subject_observations,
        column_name="extra__observation_details",
        field_name_options=["precipitation"],
        output_type="float",
        output_column_name="precipitation",
        **extract_precipitation_params,
    )
    .call()
)


# %% [markdown]
# ## Extract temperature data

# %%
# parameters

extract_temperature_params = dict()

# %%
# call the task


extract_temperature = (
    extract_value_from_json_column.set_task_instance_id("extract_temperature")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_precipitation,
        column_name="extra__observation_details",
        field_name_options=["surface_air_temperature"],
        output_type="float",
        output_column_name="temperature",
        **extract_temperature_params,
    )
    .call()
)


# %% [markdown]
# ## Extract wind speed data

# %%
# parameters

extract_wind_speed_params = dict()

# %%
# call the task


extract_wind_speed = (
    extract_value_from_json_column.set_task_instance_id("extract_wind_speed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_temperature,
        column_name="extra__observation_details",
        field_name_options=["wind_speed"],
        output_type="float",
        output_column_name="wind_speed",
        **extract_wind_speed_params,
    )
    .call()
)


# %% [markdown]
# ## Extract wind gusts data

# %%
# parameters

extract_wind_gusts_params = dict()

# %%
# call the task


extract_wind_gusts = (
    extract_value_from_json_column.set_task_instance_id("extract_wind_gusts")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_wind_speed,
        column_name="extra__observation_details",
        field_name_options=["wind_gusts"],
        output_type="float",
        output_column_name="wind_gusts",
        **extract_wind_gusts_params,
    )
    .call()
)


# %% [markdown]
# ## Extract soil temperature data

# %%
# parameters

extract_soil_temperature_params = dict()

# %%
# call the task


extract_soil_temperature = (
    extract_value_from_json_column.set_task_instance_id("extract_soil_temperature")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_wind_gusts,
        column_name="extra__observation_details",
        field_name_options=["soil_temperature"],
        output_type="float",
        output_column_name="soil_temperature",
        **extract_soil_temperature_params,
    )
    .call()
)


# %% [markdown]
# ## Extract relative humidity data

# %%
# parameters

extract_relative_humidity_params = dict()

# %%
# call the task


extract_relative_humidity = (
    extract_value_from_json_column.set_task_instance_id("extract_relative_humidity")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_soil_temperature,
        column_name="extra__observation_details",
        field_name_options=["relative_humidity"],
        output_type="float",
        output_column_name="relative_humidity",
        **extract_relative_humidity_params,
    )
    .call()
)


# %% [markdown]
# ## Extract atmospheric pressure data

# %%
# parameters

extract_pressure_params = dict()

# %%
# call the task


extract_pressure = (
    extract_value_from_json_column.set_task_instance_id("extract_pressure")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_relative_humidity,
        column_name="extra__observation_details",
        field_name_options=["atmospheric_pressure"],
        output_type="float",
        output_column_name="atmospheric_pressure",
        **extract_pressure_params,
    )
    .call()
)


# %% [markdown]
# ## Extract date

# %%
# parameters

extract_date_params = dict()

# %%
# call the task


extract_date = (
    extract_column_as_type.set_task_instance_id("extract_date")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_pressure,
        column_name="fixtime",
        output_type="date",
        output_column_name="date",
        **extract_date_params,
    )
    .call()
)


# %% [markdown]
# ## Rename value grouper columns

# %%
# parameters

rename_grouper_columns_params = dict()

# %%
# call the task


rename_grouper_columns = (
    map_columns.set_task_instance_id("rename_grouper_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        df=extract_date,
        drop_columns=[],
        retain_columns=[],
        rename_columns={"extra__subject__name": "weather_station"},
        **rename_grouper_columns_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index

# %%
# parameters

df_with_temporal_index_params = dict()

# %%
# call the task


df_with_temporal_index = (
    add_temporal_index.set_task_instance_id("df_with_temporal_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_grouper_columns,
        time_col="fixtime",
        cast_to_datetime=True,
        groupers=groupers,
        format="mixed",
        **df_with_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate weather summary table

# %%
# parameters

daily_weather_params = dict()

# %%
# call the task


daily_weather = (
    summarize_df.set_task_instance_id("daily_weather")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=df_with_temporal_index,
        groupby_cols=["weather_station", "date"],
        summary_params=[
            {
                "display_name": "precipitation",
                "aggregator": "sum",
                "column": "precipitation",
            },
            {
                "display_name": "temperature",
                "aggregator": "mean",
                "column": "temperature",
            },
            {
                "display_name": "wind_speed",
                "aggregator": "mean",
                "column": "wind_speed",
            },
            {"display_name": "wind_gusts", "aggregator": "max", "column": "wind_gusts"},
            {
                "display_name": "soil_temperature",
                "aggregator": "mean",
                "column": "soil_temperature",
            },
            {
                "display_name": "relative_humidity",
                "aggregator": "mean",
                "column": "relative_humidity",
            },
            {
                "display_name": "atmospheric_pressure",
                "aggregator": "mean",
                "column": "atmospheric_pressure",
            },
        ],
        reset_index=True,
        **daily_weather_params,
    )
    .call()
)


# %% [markdown]
# ## Perist weather summary table

# %%
# parameters

persist_weather_summary_params = dict()

# %%
# call the task


persist_weather_summary = (
    persist_df.set_task_instance_id("persist_weather_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=daily_weather,
        filename="weather_summary_table",
        **persist_weather_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Draw precipitation chart

# %%
# parameters

precipitation_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


precipitation_chart = (
    draw_line_chart.set_task_instance_id("precipitation_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        smoothing=None,
        dataframe=daily_weather,
        x_column="date",
        y_column="precipitation",
        category_column="weather_station",
        line_kwargs={"shape": "linear"},
        layout_kwargs={
            "title": None,
            "title_x": 0.01,
            "title_y": 0.95,
            "showlegend": True,
            "fontsize": 20,
            "fontcolor": "#2c3e50",
            "plot_bgcolor": "#f5f5f5",
            "xaxis": {
                "title": "Date",
                "showgrid": True,
                "gridcolor": "#e0e0e0",
                "gridwidth": 1,
                "tickformat": "%Y-%m-%d",
                "tickangle": -45,
                "rangemode": "auto",
            },
            "yaxis": {"title": "Precipitation (mm)", "tickformat": ".1f"},
            "legend_title": "Weather Station",
            "hovermode": "x unified",
        },
        **precipitation_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist precipitation chart as text

# %%
# parameters

persist_precipitation_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_precipitation = (
    persist_text.set_task_instance_id("persist_precipitation")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=precipitation_chart,
        filename="precipitation_readings_over_time.html",
        **persist_precipitation_params,
    )
    .call()
)


# %% [markdown]
# ## Draw temperature chart

# %%
# parameters

temperature_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


temperature_chart = (
    draw_line_chart.set_task_instance_id("temperature_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        smoothing=None,
        dataframe=daily_weather,
        x_column="date",
        y_column="temperature",
        category_column="weather_station",
        line_kwargs={"shape": "linear"},
        layout_kwargs={
            "title": None,
            "title_x": 0.01,
            "title_y": 0.95,
            "showlegend": True,
            "fontsize": 20,
            "fontcolor": "#2c3e50",
            "plot_bgcolor": "#f5f5f5",
            "xaxis": {
                "title": "Date",
                "tickformat": "%Y-%m-%d",
                "tickangle": -45,
                "rangemode": "auto",
            },
            "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
            "legend_title": "Weather Station",
            "hovermode": "x unified",
        },
        **temperature_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist temperature chart as text

# %%
# parameters

persist_temperature_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_temperature = (
    persist_text.set_task_instance_id("persist_temperature")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=temperature_chart,
        filename="temperature_readings_over_time.html",
        **persist_temperature_params,
    )
    .call()
)


# %% [markdown]
# ## Draw wind speed chart

# %%
# parameters

wind_speed_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


wind_speed_chart = (
    draw_line_chart.set_task_instance_id("wind_speed_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        smoothing=None,
        dataframe=daily_weather,
        x_column="date",
        y_column="wind_speed",
        category_column="weather_station",
        line_kwargs={"shape": "linear"},
        layout_kwargs={
            "title": None,
            "title_x": 0.01,
            "title_y": 0.95,
            "showlegend": True,
            "fontsize": 20,
            "fontcolor": "#2c3e50",
            "plot_bgcolor": "#f5f5f5",
            "xaxis": {
                "title": "Date",
                "tickformat": "%Y-%m-%d",
                "tickangle": -45,
                "rangemode": "auto",
            },
            "yaxis": {"title": "Average wind speed", "tickformat": ".1f"},
            "legend_title": "Weather Station",
            "hovermode": "x unified",
        },
        **wind_speed_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist wind speed chart as text

# %%
# parameters

persist_wind_speed_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_wind_speed = (
    persist_text.set_task_instance_id("persist_wind_speed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=wind_speed_chart,
        filename="wind_speed_readings_over_time.html",
        **persist_wind_speed_params,
    )
    .call()
)


# %% [markdown]
# ## Draw wind gusts chart

# %%
# parameters

wind_gusts_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


wind_gusts_chart = (
    draw_line_chart.set_task_instance_id("wind_gusts_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        smoothing=None,
        dataframe=daily_weather,
        x_column="date",
        y_column="wind_gusts",
        category_column="weather_station",
        line_kwargs={"shape": "linear"},
        layout_kwargs={
            "title": None,
            "title_x": 0.01,
            "title_y": 0.95,
            "showlegend": True,
            "fontsize": 20,
            "fontcolor": "#2c3e50",
            "plot_bgcolor": "#f5f5f5",
            "xaxis": {
                "title": "Date",
                "tickformat": "%Y-%m-%d",
                "tickangle": -45,
                "rangemode": "auto",
            },
            "yaxis": {"title": "Max wind gusts", "tickformat": ".1f"},
            "legend_title": "Weather Station",
            "hovermode": "x unified",
        },
        **wind_gusts_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist wind gusts chart as text

# %%
# parameters

persist_wind_gusts_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_wind_gusts = (
    persist_text.set_task_instance_id("persist_wind_gusts")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=wind_gusts_chart,
        filename="wind_gusts_readings_over_time.html",
        **persist_wind_gusts_params,
    )
    .call()
)


# %% [markdown]
# ## Draw soil temperature chart

# %%
# parameters

soil_temp_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


soil_temp_chart = (
    draw_line_chart.set_task_instance_id("soil_temp_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        smoothing=None,
        dataframe=daily_weather,
        x_column="date",
        y_column="soil_temperature",
        category_column="weather_station",
        line_kwargs={"shape": "linear"},
        layout_kwargs={
            "title": None,
            "title_x": 0.01,
            "title_y": 0.95,
            "showlegend": True,
            "fontsize": 20,
            "fontcolor": "#2c3e50",
            "plot_bgcolor": "#f5f5f5",
            "xaxis": {
                "title": "Date",
                "tickformat": "%Y-%m-%d",
                "tickangle": -45,
                "rangemode": "auto",
            },
            "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
            "legend_title": "Weather Station",
            "hovermode": "x unified",
        },
        **soil_temp_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist soil temperature chart as text

# %%
# parameters

persist_soil_temp_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_soil_temp = (
    persist_text.set_task_instance_id("persist_soil_temp")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=soil_temp_chart,
        filename="soil_temperature_readings_over_time.html",
        **persist_soil_temp_params,
    )
    .call()
)


# %% [markdown]
# ## Draw relative humidity chart

# %%
# parameters

rel_humidity_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


rel_humidity_chart = (
    draw_line_chart.set_task_instance_id("rel_humidity_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        smoothing=None,
        dataframe=daily_weather,
        x_column="date",
        y_column="relative_humidity",
        category_column="weather_station",
        line_kwargs={"shape": "linear"},
        layout_kwargs={
            "title": None,
            "title_x": 0.01,
            "title_y": 0.95,
            "showlegend": True,
            "fontsize": 20,
            "fontcolor": "#2c3e50",
            "plot_bgcolor": "#f5f5f5",
            "xaxis": {
                "title": "Date",
                "tickformat": "%Y-%m-%d",
                "tickangle": -45,
                "rangemode": "auto",
            },
            "yaxis": {"title": "Average humidity", "tickformat": ".1f"},
            "legend_title": "Weather Station",
            "hovermode": "x unified",
        },
        **rel_humidity_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist relative humidity chart as text

# %%
# parameters

persist_rel_humidity_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_rel_humidity = (
    persist_text.set_task_instance_id("persist_rel_humidity")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=rel_humidity_chart,
        filename="relative_humidity_readings_over_time.html",
        **persist_rel_humidity_params,
    )
    .call()
)


# %% [markdown]
# ## Draw atmospheric pressure chart

# %%
# parameters

pressure_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


pressure_chart = (
    draw_line_chart.set_task_instance_id("pressure_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        smoothing=None,
        dataframe=daily_weather,
        x_column="date",
        y_column="atmospheric_pressure",
        category_column="weather_station",
        line_kwargs={"shape": "linear"},
        layout_kwargs={
            "title": None,
            "title_x": 0.01,
            "title_y": 0.95,
            "showlegend": True,
            "fontsize": 20,
            "fontcolor": "#2c3e50",
            "plot_bgcolor": "#f5f5f5",
            "xaxis": {
                "title": "Date",
                "tickformat": "%Y-%m-%d",
                "tickangle": -45,
                "rangemode": "auto",
            },
            "yaxis": {"title": "Average pressure", "tickformat": ".1f"},
            "legend_title": "Weather Station",
            "hovermode": "x unified",
        },
        **pressure_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist atmospheric pressure chart as text

# %%
# parameters

persist_pressure_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_pressure = (
    persist_text.set_task_instance_id("persist_pressure")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=pressure_chart,
        filename="atmospheric_pressure_readings_over_time.html",
        **persist_pressure_params,
    )
    .call()
)


# %% [markdown]
# ## Convert chart htmls to png

# %%
# parameters

convert_chart_html_png_params = dict()

# %%
# call the task


convert_chart_html_png = (
    html_to_png.set_task_instance_id("convert_chart_html_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        html_path=[
            persist_precipitation,
            persist_temperature,
            persist_wind_speed,
            persist_wind_gusts,
            persist_soil_temp,
            persist_rel_humidity,
            persist_pressure,
        ],
        config={
            "width": 1280,
            "height": 720,
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 1,
            "timeout": 0,
            "max_concurrent_pages": 10,
        },
        **convert_chart_html_png_params,
    )
    .call()
)


# %% [markdown]
# ## MNC event report dashboard

# %%
# parameters

mnc_events_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


mnc_events_dashboard = (
    gather_dashboard.set_task_instance_id("mnc_events_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        widgets=[],
        time_range=time_range,
        groupers=groupers,
        **mnc_events_dashboard_params,
    )
    .call()
)
