# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    subject_observations = (
        get_subjectgroup_observations.validate()
        .set_task_instance_id("subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            include_details=False,
            include_subjectsource_details=False,
            subject_group_name="ER2ER - From GMMF",
            **(params_dict.get("subject_observations") or {}),
        )
        .call()
    )

    extract_precipitation = (
        extract_value_from_json_column.validate()
        .set_task_instance_id("extract_precipitation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_observations,
            column_name="extra__observation_details",
            field_name_options=["precipitation"],
            output_type="float",
            output_column_name="precipitation",
            **(params_dict.get("extract_precipitation") or {}),
        )
        .call()
    )

    extract_temperature = (
        extract_value_from_json_column.validate()
        .set_task_instance_id("extract_temperature")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_precipitation,
            column_name="extra__observation_details",
            field_name_options=["surface_air_temperature"],
            output_type="float",
            output_column_name="temperature",
            **(params_dict.get("extract_temperature") or {}),
        )
        .call()
    )

    extract_wind_speed = (
        extract_value_from_json_column.validate()
        .set_task_instance_id("extract_wind_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_temperature,
            column_name="extra__observation_details",
            field_name_options=["wind_speed"],
            output_type="float",
            output_column_name="wind_speed",
            **(params_dict.get("extract_wind_speed") or {}),
        )
        .call()
    )

    extract_wind_gusts = (
        extract_value_from_json_column.validate()
        .set_task_instance_id("extract_wind_gusts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_wind_speed,
            column_name="extra__observation_details",
            field_name_options=["wind_gusts"],
            output_type="float",
            output_column_name="wind_gusts",
            **(params_dict.get("extract_wind_gusts") or {}),
        )
        .call()
    )

    extract_soil_temperature = (
        extract_value_from_json_column.validate()
        .set_task_instance_id("extract_soil_temperature")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_wind_gusts,
            column_name="extra__observation_details",
            field_name_options=["soil_temperature"],
            output_type="float",
            output_column_name="soil_temperature",
            **(params_dict.get("extract_soil_temperature") or {}),
        )
        .call()
    )

    extract_relative_humidity = (
        extract_value_from_json_column.validate()
        .set_task_instance_id("extract_relative_humidity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_soil_temperature,
            column_name="extra__observation_details",
            field_name_options=["relative_humidity"],
            output_type="float",
            output_column_name="relative_humidity",
            **(params_dict.get("extract_relative_humidity") or {}),
        )
        .call()
    )

    extract_pressure = (
        extract_value_from_json_column.validate()
        .set_task_instance_id("extract_pressure")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_relative_humidity,
            column_name="extra__observation_details",
            field_name_options=["atmospheric_pressure"],
            output_type="float",
            output_column_name="atmospheric_pressure",
            **(params_dict.get("extract_pressure") or {}),
        )
        .call()
    )

    extract_date = (
        extract_column_as_type.validate()
        .set_task_instance_id("extract_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_pressure,
            column_name="fixtime",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_date") or {}),
        )
        .call()
    )

    rename_grouper_columns = (
        map_columns.validate()
        .set_task_instance_id("rename_grouper_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            df=extract_date,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"extra__subject__name": "weather_station"},
            **(params_dict.get("rename_grouper_columns") or {}),
        )
        .call()
    )

    df_with_temporal_index = (
        add_temporal_index.validate()
        .set_task_instance_id("df_with_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_grouper_columns,
            time_col="fixtime",
            cast_to_datetime=True,
            groupers=groupers,
            format="mixed",
            **(params_dict.get("df_with_temporal_index") or {}),
        )
        .call()
    )

    daily_weather = (
        summarize_df.validate()
        .set_task_instance_id("daily_weather")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=df_with_temporal_index,
            groupby_cols=["weather_station", "date"],
            summary_params=[
                {
                    "display_name": "precipitation",
                    "aggregator": "sum",
                    "column": "precipitation",
                },
                {
                    "display_name": "temperature",
                    "aggregator": "mean",
                    "column": "temperature",
                },
                {
                    "display_name": "wind_speed",
                    "aggregator": "mean",
                    "column": "wind_speed",
                },
                {
                    "display_name": "wind_gusts",
                    "aggregator": "max",
                    "column": "wind_gusts",
                },
                {
                    "display_name": "soil_temperature",
                    "aggregator": "mean",
                    "column": "soil_temperature",
                },
                {
                    "display_name": "relative_humidity",
                    "aggregator": "mean",
                    "column": "relative_humidity",
                },
                {
                    "display_name": "atmospheric_pressure",
                    "aggregator": "mean",
                    "column": "atmospheric_pressure",
                },
            ],
            reset_index=True,
            **(params_dict.get("daily_weather") or {}),
        )
        .call()
    )

    persist_weather_summary = (
        persist_df.validate()
        .set_task_instance_id("persist_weather_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=daily_weather,
            filename="weather_summary_table",
            **(params_dict.get("persist_weather_summary") or {}),
        )
        .call()
    )

    precipitation_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("precipitation_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=daily_weather,
            x_column="date",
            y_column="precipitation",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 20,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "showgrid": True,
                    "gridcolor": "#e0e0e0",
                    "gridwidth": 1,
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Precipitation (mm)", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("precipitation_chart") or {}),
        )
        .call()
    )

    persist_precipitation = (
        persist_text.validate()
        .set_task_instance_id("persist_precipitation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=precipitation_chart,
            filename="precipitation_readings_over_time.html",
            **(params_dict.get("persist_precipitation") or {}),
        )
        .call()
    )

    temperature_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("temperature_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=daily_weather,
            x_column="date",
            y_column="temperature",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 20,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("temperature_chart") or {}),
        )
        .call()
    )

    persist_temperature = (
        persist_text.validate()
        .set_task_instance_id("persist_temperature")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=temperature_chart,
            filename="temperature_readings_over_time.html",
            **(params_dict.get("persist_temperature") or {}),
        )
        .call()
    )

    wind_speed_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("wind_speed_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=daily_weather,
            x_column="date",
            y_column="wind_speed",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 20,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average wind speed", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("wind_speed_chart") or {}),
        )
        .call()
    )

    persist_wind_speed = (
        persist_text.validate()
        .set_task_instance_id("persist_wind_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=wind_speed_chart,
            filename="wind_speed_readings_over_time.html",
            **(params_dict.get("persist_wind_speed") or {}),
        )
        .call()
    )

    wind_gusts_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("wind_gusts_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=daily_weather,
            x_column="date",
            y_column="wind_gusts",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 20,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Max wind gusts", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("wind_gusts_chart") or {}),
        )
        .call()
    )

    persist_wind_gusts = (
        persist_text.validate()
        .set_task_instance_id("persist_wind_gusts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=wind_gusts_chart,
            filename="wind_gusts_readings_over_time.html",
            **(params_dict.get("persist_wind_gusts") or {}),
        )
        .call()
    )

    soil_temp_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("soil_temp_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=daily_weather,
            x_column="date",
            y_column="soil_temperature",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 20,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average Temperature (°C)", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("soil_temp_chart") or {}),
        )
        .call()
    )

    persist_soil_temp = (
        persist_text.validate()
        .set_task_instance_id("persist_soil_temp")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=soil_temp_chart,
            filename="soil_temperature_readings_over_time.html",
            **(params_dict.get("persist_soil_temp") or {}),
        )
        .call()
    )

    rel_humidity_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("rel_humidity_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=daily_weather,
            x_column="date",
            y_column="relative_humidity",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 20,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average humidity", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("rel_humidity_chart") or {}),
        )
        .call()
    )

    persist_rel_humidity = (
        persist_text.validate()
        .set_task_instance_id("persist_rel_humidity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=rel_humidity_chart,
            filename="relative_humidity_readings_over_time.html",
            **(params_dict.get("persist_rel_humidity") or {}),
        )
        .call()
    )

    pressure_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("pressure_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=daily_weather,
            x_column="date",
            y_column="atmospheric_pressure",
            category_column="weather_station",
            line_kwargs={"shape": "linear"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "fontsize": 20,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Average pressure", "tickformat": ".1f"},
                "legend_title": "Weather Station",
                "hovermode": "x unified",
            },
            **(params_dict.get("pressure_chart") or {}),
        )
        .call()
    )

    persist_pressure = (
        persist_text.validate()
        .set_task_instance_id("persist_pressure")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=pressure_chart,
            filename="atmospheric_pressure_readings_over_time.html",
            **(params_dict.get("persist_pressure") or {}),
        )
        .call()
    )

    convert_chart_html_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_chart_html_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=[
                persist_precipitation,
                persist_temperature,
                persist_wind_speed,
                persist_wind_gusts,
                persist_soil_temp,
                persist_rel_humidity,
                persist_pressure,
            ],
            config={
                "width": 1280,
                "height": 720,
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "timeout": 0,
                "max_concurrent_pages": 5,
            },
            **(params_dict.get("convert_chart_html_png") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("mnc_events_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
